export default function AIReportCard({ caseData }) {
  if (!caseData) {
    return (
      <div className="card p-6 text-center text-gray-400 text-sm">
        No AI report available for this booking
      </div>
    )
  }

  const predictions = caseData.predictions || []
  const findings = caseData.report_findings || []
  const symptoms = caseData.symptoms || []
  const transcript = caseData.voice_transcript
  const faceMarkers = caseData.face_markers || []
  const faceCondition = caseData.face_condition
  const faceConfidence = caseData.face_confidence

  const inputsUsed = [
    {
      label: 'Voice',
      icon: '🎤',
      active: !!transcript,
    },
    {
      label: 'Report',
      icon: '📄',
      active: findings.length > 0,
    },
    {
      label: 'Face Scan',
      icon: '📷',
      active: faceMarkers.length > 0,
    },
    {
      label: 'Symptoms',
      icon: '💊',
      active: symptoms.length > 0,
    },
  ]

  const confidenceColor = (index) => {
    if (index === 0) return { bar: 'bg-red-500', text: 'text-red-600' }
    if (index === 1) return { bar: 'bg-yellow-500', text: 'text-yellow-600' }
    return { bar: 'bg-green-500', text: 'text-green-600' }
  }

  const findingStatusStyle = (status) => {
    if (status === 'high' || status === 'abnormal') {
      return 'bg-red-100 text-red-600'
    }
    if (status === 'low') {
      return 'bg-yellow-100 text-yellow-600'
    }
    return 'bg-green-100 text-green-600'
  }

  return (
    <div className="card p-6 flex flex-col gap-6">

      {/* Header */}
      <div className="flex items-center justify-between">
        <h3 className="text-lg font-bold text-gray-800">
          🤖 AI Analysis Report
        </h3>
        <span className="text-xs text-gray-400 bg-gray-100 px-3 py-1
                         rounded-full font-medium">
          Generated by OrphanCure AI
        </span>
      </div>

      {/* Inputs used */}
      <div>
        <p className="section-title">Inputs Analyzed</p>
        <div className="flex flex-wrap gap-2">
          {inputsUsed.map((input, i) => (
            <div
              key={i}
              className={`flex items-center gap-2 px-3 py-1.5 rounded-full
                          text-xs font-semibold border transition-colors
                          ${input.active
                            ? 'bg-green-50 text-green-600 border-green-200'
                            : 'bg-gray-50 text-gray-300 border-gray-200'
                          }`}
            >
              <span>{input.icon}</span>
              <span>{input.label}</span>
              <span>{input.active ? '✓' : '○'}</span>
            </div>
          ))}
        </div>
      </div>

      {/* Disease Predictions */}
      {predictions.length > 0 && (
        <div>
          <p className="section-title">Disease Predictions</p>
          <div className="flex flex-col gap-3">
            {predictions.map((p, i) => (
              <div key={i} className="flex items-center gap-3">

                {/* Rank */}
                <span className={`w-6 h-6 rounded-full flex items-center
                                  justify-center text-white text-xs font-bold
                                  flex-shrink-0
                                  ${i === 0 ? 'bg-red-500'
                                    : i === 1 ? 'bg-yellow-500'
                                    : 'bg-green-500'}`}>
                  {i + 1}
                </span>

                {/* Disease name */}
                <span className="text-sm font-medium text-gray-800 flex-1
                                 min-w-0 truncate">
                  {p.disease}
                </span>

                {/* Confidence bar */}
                <div className="flex items-center gap-2 w-40 flex-shrink-0">
                  <div className="flex-1 h-2 bg-gray-100 rounded-full
                                  overflow-hidden">
                    <div
                      className={`h-full rounded-full transition-all
                                  duration-500 ${confidenceColor(i).bar}`}
                      style={{ width: `${Math.min(p.confidence, 100)}%` }}
                    />
                  </div>
                  <span className={`text-xs font-bold w-10 text-right
                                    ${confidenceColor(i).text}`}>
                    {p.confidence}%
                  </span>
                </div>

              </div>
            ))}
          </div>

          {/* Matched symptoms */}
          {predictions[0]?.matched_symptoms?.length > 0 && (
            <div className="mt-3 p-3 bg-red-50 rounded-lg border
                            border-red-100">
              <p className="text-xs text-red-500 font-semibold mb-2">
                Top match based on:
              </p>
              <div className="flex flex-wrap gap-1.5">
                {predictions[0].matched_symptoms.map((s, i) => (
                  <span key={i} className="text-xs bg-white text-red-600
                                           px-2 py-0.5 rounded-full border
                                           border-red-200">
                    {s}
                  </span>
                ))}
              </div>
            </div>
          )}
        </div>
      )}

      {/* Voice Transcript */}
      {transcript && (
        <div>
          <p className="section-title">Voice Transcript</p>
          <div className="bg-blue-50 border-l-4 border-blue-400 rounded-lg
                          p-4">
            <p className="text-sm text-gray-700 leading-relaxed italic">
              "{transcript}"
            </p>
          </div>
        </div>
      )}

      {/* Extracted Symptoms */}
      {symptoms.length > 0 && (
        <div>
          <p className="section-title">
            Extracted Symptoms ({symptoms.length})
          </p>
          <div className="flex flex-wrap gap-2">
            {symptoms.map((s, i) => (
              <span key={i} className="symptom-chip capitalize">
                {s}
              </span>
            ))}
          </div>
        </div>
      )}

      {/* Report Findings */}
      {findings.length > 0 && (
        <div>
          <p className="section-title">
            Report Findings ({findings.length})
          </p>
          <div className="flex flex-col gap-2">
            {findings.map((f, i) => (
              <div key={i} className="finding-row">
                <span className="text-sm text-gray-700 font-medium
                                 capitalize flex-1">
                  {f.finding}
                </span>
                <span className={`text-xs font-bold px-2 py-0.5 rounded-full
                                  uppercase ${findingStatusStyle(f.status)}`}>
                  {f.status}
                </span>
                {f.signal && (
                  <span className="text-xs text-gray-400 hidden sm:block">
                    → {f.signal}
                  </span>
                )}
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Face Scan Results */}
      {(faceCondition || faceMarkers.length > 0) && (
        <div>
          <p className="section-title">Face Scan Results</p>

          {faceCondition && (
            <div className="flex items-center justify-between p-3
                            bg-purple-50 rounded-lg border border-purple-100
                            mb-3">
              <div className="flex items-center gap-2">
                <span className="text-purple-500">📷</span>
                <span className="text-sm font-semibold text-gray-800">
                  {faceCondition}
                </span>
              </div>
              {faceConfidence && (
                <span className="text-xs font-bold text-purple-600
                                 bg-purple-100 px-2 py-0.5 rounded-full">
                  {faceConfidence}% confidence
                </span>
              )}
            </div>
          )}

          {faceMarkers.length > 0 && (
            <div className="flex flex-wrap gap-2">
              {faceMarkers.map((m, i) => (
                <span key={i} className="text-xs bg-purple-50 text-purple-600
                                         px-3 py-1 rounded-full border
                                         border-purple-100 font-medium">
                  {m}
                </span>
              ))}
            </div>
          )}
        </div>
      )}

      {/* Empty state */}
      {predictions.length === 0 &&
       !transcript &&
       symptoms.length === 0 &&
       findings.length === 0 && (
        <div className="text-center py-8 text-gray-400">
          <div className="text-4xl mb-3">🔬</div>
          <p className="text-sm">
            AI analysis not yet complete for this patient.
            The patient may not have completed all input steps.
          </p>
        </div>
      )}

    </div>
  )
}